version: '3.8'

services:
  mysql:
    image: mysql:8.0.40
    container_name: 127.0.0.1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network
    ports:
      - "3307:3306"

volumes:
  db_data:

networks:
  laravel_network:
    external: true
